# Generated by Django 4.2.4 on 2023-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_category_delete_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
